name: Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'chiefmikey'
    steps:
      - name: Run
        run: gh pr merge "$PR_URL" --auto --squash --subject "$COMMIT_MESSAGE"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.AUTO_MERGE }}
          COMMIT_MESSAGE: ${{ github.event.pull_request.title }}
