name: Bump-N-Pub

on:
  push:
    branches:
      - main

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.bump.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Bump Version
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_PACKAGE }}
        run: |
          git config --global user.name "Mikl Wolfe"
          git config --global user.email "wolfemikl@gmail.com"
          VERSION=$(npm version patch -m "v%s")
          git push --tags
          echo ::set-output name=TAG::"${VERSION}"

  publish-github:
    name: Publish Github
    runs-on: ubuntu-latest
    needs: version
    permissions:
      contents: read
      packages: write
    env:
      TAG: ${{ needs.version.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish npm
    runs-on: ubuntu-latest
    needs: version
    env:
      TAG: ${{ needs.version.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        run: npm publish --access public
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-release:
    name: Release
    runs-on: ubuntu-latest
    needs: [version, publish-github, publish-npm]
    env:
      TAG: ${{ needs.version.outputs.TAG }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Release Tag
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_PACKAGES }}
        run: |
          gh release create ${{ env.TAG }} --verify-tag --generate-notes --latest
