name: Update Packages

on:
  schedule:
    - cron: '* */1 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-packages:
    name: Update Packages
    runs-on: ubuntu-latest

    steps:
      - name: Set Up
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.UPDATE_PACKAGES }}

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_PACKAGES }}
        run: |
          set -x
          git config --global user.name "Mikl Wolfe"
          git config --global user.email "wolfemikl@gmail.com"
          git checkout -b update-packages
          npm i

          STATUS=0
          for package in $(jq -r '.dependencies | to_entries[] | "\(.key)@\(.value)"' package.json); do
            packageName="${package%@*}"
            v1="${package##*^}"
            v2="$(npm view "${packageName}" version)"

            if [ "${v1}" != "${v2}" ]; then
              npm i -s --save-exact "${packageName}"
              echo "${packageName} (${v1} -> ${v2})"
              STATUS=1
            fi
          done

          [ ${STATUS} -eq 0 ] && echo "Packages are already up to date"

          if git status | grep -q "Your branch is ahead"; then
            git add package.json
            git commit -am 'chore(dependencies): bump'
            git push -f origin update-packages
            gh pr create -l dependencies -t 'chore(dependencies): bump ${packageName} (${v1} -> ${v2})' -b '$(npm view ${packageName})'
          fi
