name: Update Packages

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-packages:
    name: Update Packages
    runs-on: ubuntu-latest

    steps:
      - name: Set Up
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_PACKAGES }}
        run: |
          git config --global user.name "Mikl Wolfe"
          git config --global user.email "wolfemikl@gmail.com"
          npm i

          STATUS=0
          for package in $(jq -r '.dependencies | to_entries[] | "\(.key)@\(.value)"' package.json); do
            packageName="${package%@*}"
            v1="${package##*@}"
            v1="${v1##*^}"
            v2="$(npm view "${packageName}" version)"

            if [ "${v1}" != "${v2}" ]; then
              npm i -s --no-package-lock "${packageName}"
              LABEL="${packageName} (${v1} -> ${v2})"
              MESSAGE="chore(deps): bump ${LABEL}"
              BRANCH="bump_${packageName}_(${v1}_->_${v2})"
              echo "${LABEL}"
              git checkout -b "${BRANCH}"
              git add package.json
              git commit -am "${MESSAGE}"
              git push -f origin "${BRANCH}"
              gh pr create -l dependencies -t "${MESSAGE}" -b "$(npm view ${packageName})"
              git checkout main
              echo "${LABEL}" >> $GITHUB_STEP_SUMMARY
              STATUS=1
            fi
          done

          if [ ${STATUS} -eq 0 ]; then
            echo "Packages are already up to date" >> $GITHUB_STEP_SUMMARY
          fi
